service: hobbies-app
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1
  memorySize: 128

functions:
  getUsers:
    handler: handlers/handlerTest.getUsers
    events:
      - http:
          path: user
          method: get
          cors: true

  postPostAtUser:
    handler: handlers/handlerTest.postPostAtUser
    events:
      - http:
          path: post/user/{id}
          method: post
          cors: true

  postCommentAtPost:
    handler: handlers/handlerTest.postCommentAtPost
    events:
      - http:
          path: post/comment/user/{id}
          method: post
          cors: true   

plugins:
  - serverless-offline
